// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#include "NativeUilogicGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeUilogicGen.hpp"

namespace djinni_generated {

NativeUilogicGen::NativeUilogicGen() : ::djinni::JniInterface<::usnit::UilogicGen, NativeUilogicGen>("dyno/fun/usnit/UilogicGen$CppProxy") {}

NativeUilogicGen::~NativeUilogicGen() = default;


CJNIEXPORT void JNICALL Java_dyno_fun_usnit_UilogicGen_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::usnit::UilogicGen>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_dyno_fun_usnit_UilogicGen_instance(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::usnit::UilogicGen::instance();
        return ::djinni::release(::djinni_generated::NativeUilogicGen::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_dyno_fun_usnit_UilogicGen_00024CppProxy_native_1initialize(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_config)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::usnit::UilogicGen>(nativeRef);
        auto r = ref->initialize(::djinni::String::toCpp(jniEnv, j_config));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
