// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#pragma once

#include "djinni_support.hpp"
#include "usnit_event_type.hpp"

namespace djinni_generated {

class NativeUsnitEventType final : ::djinni::JniEnum {
public:
    using CppType = ::usnit::UsnitEventType;
    using JniType = jobject;

    using Boxed = NativeUsnitEventType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeUsnitEventType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeUsnitEventType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeUsnitEventType() : JniEnum("dyno/fun/usnit/UsnitEventType") {}
    friend ::djinni::JniClass<NativeUsnitEventType>;
};

}  // namespace djinni_generated
