// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#pragma once

#include "djinni_support.hpp"
#include "usnit_type.hpp"

namespace djinni_generated {

class NativeUsnitType final : ::djinni::JniEnum {
public:
    using CppType = ::usnit::UsnitType;
    using JniType = jobject;

    using Boxed = NativeUsnitType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeUsnitType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeUsnitType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeUsnitType() : JniEnum("dyno/fun/usnit/UsnitType") {}
    friend ::djinni::JniClass<NativeUsnitType>;
};

}  // namespace djinni_generated
