// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#include "NativeUsnitEventGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeUsnitEventType.hpp"

namespace djinni_generated {

NativeUsnitEventGen::NativeUsnitEventGen() : ::djinni::JniInterface<::usnit::UsnitEventGen, NativeUsnitEventGen>() {}

NativeUsnitEventGen::~NativeUsnitEventGen() = default;

NativeUsnitEventGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeUsnitEventGen::JavaProxy::~JavaProxy() = default;

bool NativeUsnitEventGen::JavaProxy::callback(::usnit::UsnitEventType c_id, const std::string & c_data) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeUsnitEventGen>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_callback,
                                          ::djinni::get(::djinni_generated::NativeUsnitEventType::fromCpp(jniEnv, c_id)),
                                          ::djinni::get(::djinni::String::fromCpp(jniEnv, c_data)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
