// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

package dyno.fun.usnit;

public enum UsnitEventType {
    CB_NONE,
    CB_DOLLAR_RT,
    CB_RMB_RT,
    CB_RATEINFO,
    ;
}
