// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

package dyno.fun.usnit;

/** @import "gearsbox/gearsbox.djinni" */
public enum UsnitType {
    TYPE_NONE,
    TYPE_METER,
    TYPE_CMETER,
    TYPE_KMETER,
    TYPE_FEET,
    TYPE_INCH,
    TYPE_MILE,
    TYPE_YARD,
    TYPE_LITRE,
    TYPE_MLITRE,
    TYPE_GAL,
    TYPE_GRAM,
    TYPE_KGRAM,
    TYPE_POUND,
    TYPE_OZ,
    TYPE_SQM,
    TYPE_SQCM,
    TYPE_SQF,
    TYPE_CELSI,
    TYPE_FAHRE,
    TYPE_SQINCH,
    TYPE_DOLLAR,
    TYPE_RMB,
    TYPE_RATE,
    TYPE_MAX,
    ;
}
