// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

package dyno.fun.usnit;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class UsnitEventGen {
    public abstract boolean callback(UsnitEventType id, String data);

    private static final class CppProxy extends UsnitEventGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public boolean callback(UsnitEventType id, String data)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_callback(this.nativeRef, id, data);
        }
        private native boolean native_callback(long _nativeRef, UsnitEventType id, String data);
    }
}
