// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

package dyno.fun.usnit;

public abstract class UsnitEventGen {
    public abstract boolean callback(UsnitEventType id, String data);
}
