// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#import <Foundation/Foundation.h>
@class USNUilogicGen;


@interface USNUilogicGen : NSObject

+ (nullable USNUilogicGen *)instance;

- (BOOL)initialize:(nonnull NSString *)config;

@end
