// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#include "usnit_event_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol USNUsnitEventGen;

namespace djinni_generated {

class UsnitEventGen
{
public:
    using CppType = std::shared_ptr<::usnit::UsnitEventGen>;
    using CppOptType = std::shared_ptr<::usnit::UsnitEventGen>;
    using ObjcType = id<USNUsnitEventGen>;

    using Boxed = UsnitEventGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

