// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, USNUsnitEventType)
{
    USNUsnitEventTypeCBNONE,
    USNUsnitEventTypeCBDOLLARRT,
    USNUsnitEventTypeCBRMBRT,
    USNUsnitEventTypeCBRATEINFO,
};
