// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#include "usnit_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class USNUsnitGen;

namespace djinni_generated {

class UsnitGen
{
public:
    using CppType = std::shared_ptr<::usnit::UsnitGen>;
    using CppOptType = std::shared_ptr<::usnit::UsnitGen>;
    using ObjcType = USNUsnitGen*;

    using Boxed = UsnitGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

