// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#import "USNUsnitEventType.h"
#import <Foundation/Foundation.h>


@protocol USNUsnitEventGen

- (BOOL)callback:(USNUsnitEventType)id
            data:(nonnull NSString *)data;

@end
