// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#import <Foundation/Foundation.h>

/** @import "gearsbox/gearsbox.djinni" */
typedef NS_ENUM(NSInteger, USNUsnitType)
{
    USNUsnitTypeTYPENONE,
    USNUsnitTypeTYPEMETER,
    USNUsnitTypeTYPECMETER,
    USNUsnitTypeTYPEKMETER,
    USNUsnitTypeTYPEFEET,
    USNUsnitTypeTYPEINCH,
    USNUsnitTypeTYPEMILE,
    USNUsnitTypeTYPEYARD,
    USNUsnitTypeTYPELITRE,
    USNUsnitTypeTYPEMLITRE,
    USNUsnitTypeTYPEGAL,
    USNUsnitTypeTYPEGRAM,
    USNUsnitTypeTYPEKGRAM,
    USNUsnitTypeTYPEPOUND,
    USNUsnitTypeTYPEOZ,
    USNUsnitTypeTYPESQM,
    USNUsnitTypeTYPESQCM,
    USNUsnitTypeTYPESQF,
    USNUsnitTypeTYPECELSI,
    USNUsnitTypeTYPEFAHRE,
    USNUsnitTypeTYPESQINCH,
    USNUsnitTypeTYPEDOLLAR,
    USNUsnitTypeTYPERMB,
    USNUsnitTypeTYPERATE,
    USNUsnitTypeTYPEMAX,
};
