// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#pragma once

#include <memory>
#include <string>

namespace usnit {

class UilogicGen {
public:
    virtual ~UilogicGen() {}

    static std::shared_ptr<UilogicGen> instance();

    virtual bool initialize(const std::string & config) = 0;
};

}  // namespace usnit
