// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#pragma once

#include <functional>

namespace usnit {

enum class UsnitEventType : int {
    CB_NONE,
    CB_DOLLAR_RT,
    CB_RMB_RT,
    CB_RATEINFO,
};

}  // namespace usnit

namespace std {

template <>
struct hash<::usnit::UsnitEventType> {
    size_t operator()(::usnit::UsnitEventType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
