// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from usnit.djinni

#pragma once

#include <memory>
#include <string>

namespace usnit {

class UsnitEventGen;
enum class LangType;
enum class UsnitType;

class UsnitGen {
public:
    virtual ~UsnitGen() {}

    static std::shared_ptr<UsnitGen> instance();

    virtual bool initialize(const std::string & conf, LangType lang, const std::shared_ptr<UsnitEventGen> & callback) = 0;

    virtual bool save() = 0;

    virtual void setType(UsnitType type) = 0;

    virtual void setInput(float value) = 0;

    virtual std::string getResult(UsnitType type) = 0;

    virtual std::string getUnitName(UsnitType type) = 0;

    virtual UsnitType getLongType() = 0;

    virtual UsnitType getMassType() = 0;

    virtual UsnitType getSquareType() = 0;

    virtual UsnitType getVolumeType() = 0;

    virtual void buildui(const std::string & view_name) = 0;
};

}  // namespace usnit
